function [x f]=demo(x)
	optMinFunc = struct('Display', 'FULL',...
    'Method', 'lbfgs',...
    'DerivativeCheck', 'off',...
    'LS_type', 1,...
    'MaxIter', 1000,...
	'LS_interp', 1,...
    'MaxFunEvals', 1000000,...
    'Corr' , 100,...
    'optTol', 1e-15,...
    'progTol', 1e-15);
	[x f] = minFunc(@funC, x, optMinFunc);

end

function [f g]=funC(x)
if x>1 && x<15
	f=x*x;
	g=2.0*x;
else
	f=inf
	g=inf
end


end
